# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Blog of Os!
email: spam-me-not@osborne1992.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site - Whatever the url is from git hub for instance
twitter_username: Osborne1992
github_username:  Osborne1992

# Build settings
markdown: kramdown

exclude: ['README.md', 'GEMFILE', 'GEMFILE.lock']

paginate: 3

gems: [jekyll-paginate]